services:
  - type: web
    name: tt-otp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
      - key: CHAT_ID
        sync: false
      - key: BOT_TOKEN
        sync: false
    preInstall:
      - sudo apt-get update
      - sudo apt-get install -y libatk1.0-0t64 libatk-bridge2.0-0t64 libcups2t64 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2t64 libatspi2.0-0t64
